default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: admin
  password: Ndt_17021009

development:
  <<: *default
  database: better_team

test:
  <<: *default
  database: test_better_team

production:
  <<: *default
  database: product_better_team
